# Generated by Django 5.2.6 on 2025-09-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPorile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
